### ISSUE TITLE
What's the supported Node version?

### ISSUE THREAD

**Issue by rngtng** [okcoker/TrelloToGithubProjects#38]
Hey Hey

I'd like to run this great project on my local machine, but don't get is compiled. The dockerfile  image looks like this so far. But I keep getting errors... any idea?

```
FROM node:<version>-buster

RUN apt update && apt install python2

RUN mkdir /app
COPY . /app

WORKDIR /app

RUN yarn
```

**Comment by rngtng** [comment]
For node 12 I get following error. alls other above are similar

```
 error: no matching function for call to 'v8::Function::New(v8::Isolate*&, void (&)(const v8::FunctionCallbackInfo<v8::Value>&), v8::Local<v8::Object>&)'
```

**Comment by rngtng** [comment]
Ah ok, node 10 it is :)

**Comment by okcoker** [comment]
Ah yes I haven't ran this in a while but look at the commit dates, I think Node 10 was probably what was on my machine at the time. You got it running with Node 10?

**Comment by rngtng** [comment]
Yes. Node 10 did it. Thx
